<a href="https://colab.research.google.com/github/mohyunyang/MyStudy/blob/master/CV_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import numpy as np
import sys

# 원 그리기

In [ ]:
img1 = cv2.imread('CV/fig/puppy.bmp')
img2 = img1[200:400, 300:500] # (y축,x축)
img3 = img2.copy()

# circle(img, center, radius, color[, thickness[, lineType[, shift]]])
cv2.circle(img2, (100,100),50, (0,0,255), 3, cv2.LINE_4)

cv2.imshow('image', img1)
cv2.imshow('image2', img2)
cv2.imshow('image3', img3)

cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
img2.shape

(200, 200, 3)

## 작은 미션

In [ ]:
img1 = cv2.imread('CV/fig/puppy.bmp')

img1[160:240, 230:500] = 0
cv2.circle(img1, (320,200),30, (30,80,130), 6, cv2.LINE_4)
cv2.circle(img1, (420,200),30, (30,80,130), 6, cv2.LINE_4)
cv2.circle(img1, (320,200),10, (30,80,130), 12, cv2.LINE_4)
cv2.circle(img1, (420,200),10, (30,80,130), 12, cv2.LINE_4)

cv2.imshow('image', img1)

cv2.waitKey()
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


# 합성

In [ ]:
import cv2
import numpy as np
import sys

In [ ]:
src = cv2.imread('CV/fig/airplane.bmp', cv2.IMREAD_COLOR)
mask = cv2.imread('CV/fig/mask_plane.bmp',cv2.IMREAD_GRAYSCALE)
dst = cv2.imread('CV/fig/field.bmp', cv2.IMREAD_COLOR)

if src is None or mask is None or dst is None:
    print('Image read failed')
    sys.exit()
    
# copyTo(src, mask[, dst]) -> dst
cv2.copyTo(src, mask, dst)
# dst = cv2.copyTo(src, mask)
    
cv2.imshow('image1', src)
cv2.imshow('image2', mask)
cv2.imshow('image3', dst)

cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
src = cv2.imread('CV/fig/cow.png')
dst = cv2.imread('CV/fig/green.png')

src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

# threshold(src, thresh, maxval, type[, dst]) -> retval, dst
ret, src_mask = cv2.threshold(src_gray, 244, 255, cv2.THRESH_BINARY_INV)

h,w = src.shape[:2]
# print("h :", h, "w :",w)

dst = cv2.resize(dst, (w, h), interpolation = cv2.INTER_AREA)

# copyTo(src, mask[, dst]) -> dst
cv2.copyTo(src, src_mask, dst)

cv2.imshow('src', src)
cv2.imshow('src_gray', src_gray)
cv2.imshow('src_mask', src_mask)
cv2.imshow('dst', dst)

cv2.waitKey()
cv2.destroyAllWindows()

 시도

In [ ]:
src = cv2.imread('CV/fig/cow.png', cv2.IMREAD_COLOR)
mask = cv2.imread('CV/fig/mask.png',cv2.IMREAD_GRAYSCALE)
dst = cv2.imread('CV/fig/green.png', cv2.IMREAD_COLOR)

cv2.namedWindow('dst', cv2.WINDOW_AUTOSIZE)
cv2.copyTo(src, mask, dst)

cv2.imshow('src', src)
cv2.imshow('mask', mask)
cv2.imshow('dst', dst)

cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
src = cv2.imread('CV/fig/cow.png')
dst = cv2.imread('CV/fig/green.png')

src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
# threshold(src, thresh, maxval, type[, dst]) -> retval, dst
ret, src_mask = cv2.threshold(src_gray, 244, 255, cv2.THRESH_BINARY_INV)

h,w = src.shape[:2]
# print("h :", h, "w :",w)

dst_crop = dst[400:400+h, 700:700+w]
#dst = cv2.resize(dst, (w, h), interpolation = cv2.INTER_AREA)

# copyTo(src, mask[, dst]) -> dst
cv2.copyTo(src, src_mask, dst_crop)

cv2.imshow('dst', dst)

cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
src.shape

(600, 600, 3)